module.exports.ADD_SAMPLE_CONTENT_DEFAULT = true;
module.exports.ADD_SAMPLE_CONTENT_MESSAGE = 'Add sample content?';
module.exports.ADD_SAMPLE_CONTENT_VAR = 'addSampleContent';

module.exports.COLLECTION_DESCRIPTION_DEFAULT = '';
module.exports.COLLECTION_DESCRIPTION_MESSAGE =
  'Collection description (optional)';
module.exports.COLLECTION_DESCRIPTION_SAMPLE =
  'Sample collection autogenerated';
module.exports.COLLECTION_DESCRIPTION_VAR = 'collectionDescription';

module.exports.COLLECTION_NAME_MESSAGE = 'Collection name';
module.exports.COLLECTION_NAME_SAMPLE = 'Sample collection';
module.exports.COLLECTION_NAME_VAR = 'collectionName';

module.exports.COLLECTION_SLUG_SAMPLE = 'sample-collection';
module.exports.COLLECTION_SLUG_VAR = 'collectionSlug';

module.exports.FRAGMENT_COLLECTION_SLUG_MESSAGE = 'Choose a collection';
module.exports.FRAGMENT_COLLECTION_SLUG_VAR = 'fragmentCollectionSlug';

module.exports.FRAGMENT_DESCRIPTION_DEFAULT = '';
module.exports.FRAGMENT_DESCRIPTION_MESSAGE = 'Fragment description (optional)';
module.exports.FRAGMENT_DESCRIPTION_SAMPLE = 'Sample fragment autogenerated';
module.exports.FRAGMENT_DESCRIPTION_VAR = 'fragmentDescription';

module.exports.FRAGMENT_NAME_MESSAGE = 'Fragment name';
module.exports.FRAGMENT_NAME_SAMPLE = 'Sample fragment';
module.exports.FRAGMENT_NAME_VAR = 'fragmentName';

module.exports.FRAGMENT_SLUG_VAR = 'fragmentSlug';

module.exports.FRAGMENT_TYPE_DEFAULT = 'section';
module.exports.FRAGMENT_TYPE_MESSAGE = 'Fragment type';
module.exports.FRAGMENT_TYPE_OPTIONS = [
	{name: 'Section', value: 'section'},
	{name: 'Element', value: 'element'},
];
module.exports.FRAGMENT_TYPE_VAR = 'fragmentType';

module.exports.IMPORT_WATCH_VAR = 'watch';

module.exports.LIFERAY_COMPANYID_MESSAGE = 'Company ID';
module.exports.LIFERAY_COMPANYID_VAR = 'companyId';

module.exports.LIFERAY_GROUPID_MESSAGE = 'Group ID';
module.exports.LIFERAY_GROUPID_VAR = 'groupId';

module.exports.LIFERAY_HOST_DEFAULT = 'http://localhost:8080';
module.exports.LIFERAY_HOST_MESSAGE = 'Liferay host & port';
module.exports.LIFERAY_HOST_VAR = 'host';

module.exports.LIFERAY_PASSWORD_DEFAULT = 'test';
module.exports.LIFERAY_PASSWORD_MESSAGE = 'Password';
module.exports.LIFERAY_PASSWORD_VAR = 'password';

module.exports.LIFERAY_USERNAME_DEFAULT = 'test@liferay.com';
module.exports.LIFERAY_USERNAME_MESSAGE = 'Username';
module.exports.LIFERAY_USERNAME_VAR = 'username';

module.exports.NEW_COLLECTION_MESSAGE = '+ New collection';
module.exports.NEW_COLLECTION_SHORT = '(new)';
module.exports.NEW_COLLECTION_VALUE = '__NEW_COLLECTION_VALUE__';

module.exports.PROJECT_NAME_DEFAULT = 'Sample Liferay Fragments';
module.exports.PROJECT_NAME_MESSAGE = 'Project name';
module.exports.PROJECT_NAME_VAR = 'projectName';

module.exports.PROJECT_SLUG_VAR = 'projectSlug';
